site_name: Orbital Docs
site_description: Official Documentation for the Orbital CLI Framework
site_author: Orbital Team
site_url: 'https://docs.orbital.sh'
theme:
  name: material
  palette:
    primary: blue
    accent: green
  feature:
    tabs: true
repo_name: orbital-js/docs
repo_url: 'https://github.com/orbital-js/docs'
extra:
  social:
    - type: github
      link: 'https://github.com/orbital-js'
    - type: twitter
      link: 'https://twitter.com/nestframework'
    - type: globe
      link: http://orbital.sh
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - assets/scripts/load-contributors.js
extra_css:
  - assets/styles/custom.css
copyright: Copyright &copy; 2018 - Orbital Team. Docs are served under the MIT License.
pages:
  - Home: index.md
  - Guide:
      - Introduction: guide/introduction.md
      - CLI: guide/cli.md
      - Commands: guide/commands.md
      - Params: guide/params.md
      - Options: guide/options.md
      - Subcommands: guide/subcommands.md
      - Publishing: guide/publishing.md
  - API:
      - Core:
          - CLI: api/core/cli.md
          - Command: api/core/command.md
          - Executable: api/core/executable.md
          - Option: api/core/option.md
          - OrbitalFactory: api/core/orbital-factory.md
          - Param: api/core/param.md
          - SubcommandGroup: api/core/subcommand-group.md